### ISSUE TITLE
Yarn error

### ISSUE THREAD

**Issue by nicholas-santos** [ConduitVC/appsync-serverless-emulator-example#4]
I get this error when trying to run Yarn on the project directory

`yarn install v1.9.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > graphql-tag@2.9.2" has unmet peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning " > react-apollo@2.1.4" has unmet peer dependency "apollo-client@^2.2.3".
warning "@conduitvc/appsync-emulator-serverless > @conduitvc/dynamodb-emulator@0.5.0" has incorrect peer dependency "aws-sdk@^2.260.1".
warning "neutrino-preset-conduit > eslint-config-prettier@2.9.0" has unmet peer dependency "eslint@>=3.14.1".
warning "neutrino-preset-conduit > eslint-plugin-flowtype@2.49.3" has unmet peer dependency "eslint@>=2.0.0".
warning "neutrino-preset-conduit > fork-ts-checker-webpack-plugin@0.3.0" has unmet peer dependency "webpack@^2.3.0 || ^3.0.0".
warning "neutrino-preset-conduit > @neutrinojs/airbnb > @neutrinojs/eslint > eslint-loader@2.0.0" has unmet peer dependency "webpack@>=2.0.0 <5.0.0".
[4/4] Building fresh packages...
[1/16] ⠠ fs-ext
[2/16] ⠠ snappy
[3/16] ⠠ kerberos
[4/16] ⠠ fs-ext
warning Error running install script for optional dependency: "C:\\Users\\nicho\\Documents\\appsync-emulator\\node_modules\\snappy: Command failed.
Exit code: 1
Command: .\\node_modules\\.bin\\node-gyp rebuild
Arguments:
Directory: C:\\Users\\nicho\\Documents\\appsync-emulator\\node_modules\\snappy
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@8.10.0 | win32 | x64
gyp info spawn C:\\Python27\\python.EXE
gyp info spawn args [ 'C:\\\\Users\\\\nicho\\\\Documents\\\\appsync-emulator\\\\node_modules\\\\snappy\\\\node_modules\\\\node-gyp\\\\gyp\\\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\nicho\\\\Documents\\\\appsync-emulator\\\\node_modules\\\\snappy\\\\build\\\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\nicho\\\\Documents\\\\appsync-emulator\\\\node_modules\\\\snappy\\\\node_modules\\\\node-gyp\\\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\nicho\\\\.node-gyp\\\\8.10.0\\\\include\\\\node\\\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\\\Users\\\\nicho\\\\.node-gyp\\\\8.10.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\\\Users\\\\nicho\\\\Documents\\\\appsync-emulator\\\\node_modules\\\\snappy\\\\node_modules\\\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\\\Users\\\\nicho\\\\Documents\\\\appsync-emulator\\\\node_modules\\\\snappy',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\\\Users\\\\nicho\\\\Documents\\\\appsync-emulator\\\\node_modules\\\\snappy\\\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the \"/m\" switch.
MSBUILD : error MSB4132: The tools version \"2.0\" is unrecognized. Available tools versions are \"4.0\".
gyp ERR! build error
gyp ERR! stack Error: `C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\\Users\\nicho\\Documents\\appsync-emulator\\node_modules\\snappy\\node_modules\\node-gyp\\lib\\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Users\\\\nicho\\\\Documents\\\\appsync-emulator\\\\node_modules\\\\snappy\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"
gyp ERR! cwd C:\\Users\\nicho\\Documents\\appsync-emulator\\node_modules\\snappy
[1/16] ⠄ fs-ext
[6/16] ⠄ leveldown
[3/16] ⠄ kerberos
[4/16] ⠄ fs-ext
error C:\Users\nicho\Documents\appsync-emulator\node_modules\fs-ext: Command failed.
Exit code: 1
Command: node-gyp configure build
Arguments:
Directory: C:\Users\nicho\Documents\appsync-emulator\node_modules\fs-ext
Output:
C:\Users\nicho\Documents\appsync-emulator\node_modules\fs-ext>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build )  else (node "" configure build )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.10.0 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\nicho\\Documents\\appsync-emulator\\node_modules\\fs-ext\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\nicho\\.node-gyp\\8.10.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\nicho\\.node-gyp\\8.10.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\nicho\\.node-gyp\\8.10.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\nicho\\Documents\\appsync-emulator\\node_modules\\fs-ext',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\nicho\\Documents\\appsync-emulator\\node_modules\\fs-ext\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\nicho\Documents\appsync-emulator\node_modules\fs-ext

warning Error running install script for optional dependency: "C:\\Users\\nicho\\Documents\\appsync-emulator\\node_modules\\qlobber-fsq\\node_modules\\fs-ext: Command failed.
Exit code: 1
Command: node-gyp configure build
Arguments:
Directory: C:\\Users\\nicho\\Documents\\appsync-emulator\\node_modules\\qlobber-fsq\\node_modules\\fs-ext
Output:
C:\\Users\\nicho\\Documents\\appsync-emulator\\node_modules\\qlobber-fsq\\node_modules\\fs-ext>if not defined npm_config_node_gyp (node \"C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" configure build )  else (node \"\" configure build )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.10.0 | win32 | x64
gyp info spawn C:\\Python27\\python.EXE
gyp info spawn args [ 'C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\gyp\\\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\nicho\\\\Documents\\\\appsync-emulator\\\\node_modules\\\\qlobber-fsq\\\\node_modules\\\\fs-ext\\\\build\\\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\nicho\\\\.node-gyp\\\\8.10.0\\\\include\\\\node\\\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\\\Users\\\\nicho\\\\.node-gyp\\\\8.10.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\nicho\\\\.node-gyp\\\\8.10.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\\\Users\\\\nicho\\\\Documents\\\\appsync-emulator\\\\node_modules\\\\qlobber-fsq\\\\node_modules\\\\fs-ext',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\\\Users\\\\nicho\\\\Documents\\\\appsync-emulator\\\\node_modules\\\\qlobber-fsq\\\\node_modules\\\\fs-ext\\\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the \"/m\" switch.
MSBUILD : error MSB4132: The tools version \"2.0\" is unrecognized. Available tools versions are \"4.0\".
gyp ERR! build error
gyp ERR! stack Error: `C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\lib\\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"configure\" \"build\"
gyp ERR! cwd C:\\Users\\nicho\\Documents\\appsync-emulator\\node_modules\\qlobber-fsq\\node_modules\\fs-ext
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
warning Error running install script for optional dependency: "C:\\Users\\nicho\\Documents\\appsync-emulator\\node_modules\\zmq: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\\Users\\nicho\\Documents\\appsync-emulator\\node_modules\\zmq
Output:
C:\\Users\\nicho\\Documents\\appsync-emulator\\node_modules\\zmq>if not defined npm_config_node_gyp (node \"C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"\" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.10.0 | win32 | x64
gyp info spawn C:\\Python27\\python.EXE
gyp info spawn args [ 'C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\gyp\\\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\nicho\\\\Documents\\\\appsync-emulator\\\\node_modules\\\\zmq\\\\build\\\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\nicho\\\\.node-gyp\\\\8.10.0\\\\include\\\\node\\\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\\\Users\\\\nicho\\\\.node-gyp\\\\8.10.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\nicho\\\\.node-gyp\\\\8.10.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\\\Users\\\\nicho\\\\Documents\\\\appsync-emulator\\\\node_modules\\\\zmq',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\\\Users\\\\nicho\\\\Documents\\\\appsync-emulator\\\\node_modules\\\\zmq\\\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the \"/m\" switch.
MSBUILD : error MSB4132: The tools version \"2.0\" is unrecognized. Available tools versions are \"4.0\".
gyp ERR! build error
gyp ERR! stack Error: `C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\lib\\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"
gyp ERR! cwd C:\\Users\\nicho\\Documents\\appsync-emulator\\node_modules\\zmq
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
warning Error running install script for optional dependency: "C:\\Users\\nicho\\Documents\\appsync-emulator\\node_modules\\leveldown: Command failed.
Exit code: 2
Command: prebuild --install
Arguments:
Directory: C:\\Users\\nicho\\Documents\\appsync-emulator\\node_modules\\leveldown
Output:
prebuild info begin Prebuild version 4.5.0
gyp http GET https://nodejs.org/download/release/v8.10.0/node-v8.10.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v8.10.0/node-v8.10.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v8.10.0/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v8.10.0/win-x64/node.lib
gyp http GET https://nodejs.org/download/release/v8.10.0/win-x86/node.lib
gyp http 200 https://nodejs.org/download/release/v8.10.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v8.10.0/win-x86/node.lib
gyp http 200 https://nodejs.org/download/release/v8.10.0/win-x64/node.lib
gyp info spawn C:\\Python27\\python.EXE
gyp info spawn args [ 'C:\\\\Users\\\\nicho\\\\Documents\\\\appsync-emulator\\\\node_modules\\\\node-gyp\\\\gyp\\\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\nicho\\\\Documents\\\\appsync-emulator\\\\node_modules\\\\leveldown\\\\build\\\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\nicho\\\\Documents\\\\appsync-emulator\\\\node_modules\\\\node-gyp\\\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\nicho\\\\Documents\\\\appsync-emulator\\\\node_modules\\\\leveldown\\\\8.10.0\\\\include\\\\node\\\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\\\Users\\\\nicho\\\\Documents\\\\appsync-emulator\\\\node_modules\\\\leveldown\\\\8.10.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\\\Users\\\\nicho\\\\Documents\\\\appsync-emulator\\\\node_modules\\\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\nicho\\\\Documents\\\\appsync-emulator\\\\node_modules\\\\leveldown\\\\8.10.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\\\Users\\\\nicho\\\\Documents\\\\appsync-emulator\\\\node_modules\\\\leveldown',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\\\Users\\\\nicho\\\\Documents\\\\appsync-emulator\\\\node_modules\\\\leveldown\\\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the \"/m\" switch.
MSBUILD : error MSB4132: The tools version \"2.0\" is unrecognized. Available tools versions are \"4.0\".
prebuild ERR! build error
prebuild ERR! stack Error: `C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\msbuild.exe` failed with exit code: 1
prebuild ERR! stack     at ChildProcess.onExit (C:\\Users\\nicho\\Documents\\appsync-emulator\\node_modules\\node-gyp\\lib\\build.js:262:23)
prebuild ERR! stack     at emitTwo (events.js:126:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:214:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
prebuild ERR! not ok
prebuild ERR! build Error: `C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\msbuild.exe` failed with exit code: 1
prebuild ERR! build     at ChildProcess.onExit (C:\\Users\\nicho\\Documents\\appsync-emulator\\node_modules\\node-gyp\\lib\\build.js:262:23)
prebuild ERR! build     at emitTwo (events.js:126:13)
prebuild ERR! build     at ChildProcess.emit (events.js:214:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)"
`

**Comment by educacionsinnombre** [comment]
Woah. Found the root cause of all of my problems
@lightsofapollo Thanks for the message. Wouldn't it be good to make a comment in the git repository? I driving myself mad on why wouldn't appsync run on Windows 10. 

I'll use the Ubuntu on Win10 to overcome this... please update it on the repo!
